name: drupal-cms
type: drupal
docroot: web
php_version: "8.4"
webserver_type: nginx-fpm
database:
  type: mysql
  version: "8.0"
corepack_enable: true

hooks:
  post-start:
    - exec: bash /var/www/html/.ddev/scripts/setup.sh
